### PR TITLE
fix the bug Exception in SingleInstance.__del__ #14

### LINKED ISSUE #14: Exception in SingleInstance.__del__
Perhaps harmless.

```
mySystem:myappdir myuser$ nosetests-3.4
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-usr-local-bin-nosetests-3-.lock
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x104af9c18>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 63, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
mySystem:myappdir myuser$ 
```

Or when commenting out the two imports suggested by @efairon in #12 : 

```
mySystem:myappdir myuser$ nosetests-3.4
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-usr-local-bin-nosetests-3-.lock
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
'NoneType' object is not iterable
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x102f7cbe0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 83, in __del__
SystemExit: -1
mySystem:myappdir myuser$ 
```

Running my app seems to work, with tendo keeping other instances from starting, but that ignored exception shows up again when I exit using ctrl-c

```
mySystem:myappdir myuser$ python3 myappdir/myapp.py
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-Users-myuser-factory-Py-myapp-myapp-myapp-.lock
please Control-C to exit myapp
RUNNING myapp
^CCLOSING myapp
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x10ced8128>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 63, in __del__
ImportError: import of 'sys' halted; None in sys.modules
mySystem:myappdir myuser$ 
```
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31821813-exception-in-singleinstance-__del__?utm_campaign=plugin&utm_content=tracker%2F446395&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F446395&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fx-kirin**
This will fix #14 .

The error depends on the Python version. It won't happen on Python 2.7.

The reason is explained [here](https://stackoverflow.com/a/14986683/1903430).

### CODE REVIEW

**Comment by fx-kirin** [comment]
That's not me put the logger instance in the global variable. It's originally there.

https://github.com/pycontribs/tendo/blob/343482e7b04a43382bf66b43708a170da6af02fe/tendo/singleton.py#L142-L143

I think it could be call in the `__main__` method of the class and not add the handler.

**Comment by fx-kirin** [comment]
I will fix it if you want.

**Comment by ssbarnea** [comment]
Please fix it, I no longer use the library myself but I will support anyone that wants to add fixes to it by doing reviews and releases.

**Comment by ssbarnea** [comment]
Reopen if you fix the branch.

**Pull request closed without merging**
